Repository stabilitydao/stability, pull requests merged in 2024-10, with the labels that each got.

#34 0.15.1: api types update (add time, usersEarned, leaderboard)
  package.json
  src/api.types.ts
Labels: enhancement

#67 0.19.1
  package.json
  src/api.types.ts
  src/contests.ts
  tools/overview-full.ts
  tools/overview.ts
Labels: 🏆 Yield Contests

#76 ♻️ real dev, tpf dev
  src/chains.ts
  src/strategies.ts
Labels: ♻️ SYNC

#77 🪙 real: sacra, usdc
  src/assets.ts
  src/stability.tokenlist.json
Labels: 🌐 DeFi Landscape

#75 🌐 add Dezswap
  src/integrations.ts
Labels: 🌐 DeFi Landscape

#73 📦 0.20.0 collector
  .github/workflows/prettier.yml
  .prettierignore
  .prettierrc
  README.md
  jest.config.js
  package.json
  src/addresses.ts
  src/api.types.ts
  src/assets.ts
  src/bridges.ts
  src/chains.ts
  src/contests.ts
  src/deployments.ts
  src/index.ts
  src/integrations.ts
  src/seeds.ts
  src/stability.tokenlist.json
  src/strategies.ts
  tests/assets.test.ts
  tests/bridges.test.ts
  tests/chains.test.ts
  tests/contests.test.ts
  tests/index.test.ts
  tests/integrations.test.ts
  tests/integrity.test.ts
  tests/strategies.test.ts
  tools/contests-maker.ts
  tools/create-contests.ts
  tools/draw-chains.ts
  tools/issue.ts
  tools/overview-full.ts
  tools/overview.ts
  tsconfig.json
  yarn.lock
Labels: 🔨 refactoring, 🌐 DeFi Landscape, 🎇 CONTENT GENERATOR, 🏆 Yield Contests, SETUP | CI, ♻️ SYNC

#84 🎇 draw integrations | 🌐 add ProtocolStatusInfo to Integrations | ⛓ add chain Hela | 🌐 add Cytoswap
  README.md
  chains.png
  integrations.png
  package.json
  src/bridges.ts
  src/chains.ts
  src/integrations.ts
  tools/draw-integrations.ts
Labels: 🌐 DeFi Landscape, 🎇 CONTENT GENERATOR

#88 💲implement -> strategy.protocols
  src/strategies.ts
Labels: 🔨 refactoring

#89 ♻️ Re.al and TPF: awaiting deployment
  chains.png
  integrations.png
  src/chains.ts
  src/strategies.ts
Labels: ♻️ SYNC

#91 ♻️ Re.al deployment
  chains.png
  integrations.png
  package.json
  src/chains.ts
  src/deployments.ts
  src/strategies.ts
Labels: ♻️ SYNC

#92 📦 0.21.1 collector
  chains.png
  integrations.png
  package.json
  src/chains.ts
  src/deployments.ts
  src/strategies.ts
Labels: ♻️ SYNC
